-- MySQL Script generated by MySQL Workbench
-- lun 09 may 2016 20:25:23 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_udla_sig
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_udla_sig
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_udla_sig` DEFAULT CHARACTER SET utf8 ;
USE `bd_udla_sig` ;

-- -----------------------------------------------------
-- Table `bd_udla_sig`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_udla_sig`.`Bloque` (
  `idBloque` INT NOT NULL AUTO_INCREMENT,
  `NumBloque` INT(11) NULL,
  `Area` DOUBLE NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idBloque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_udla_sig`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_udla_sig`.`Sala` (
  `idSala` INT NOT NULL AUTO_INCREMENT,
  `NombreSala` VARCHAR(45) NULL,
  `Latitud` VARCHAR(45) NULL,
  `Longitud` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `NumPiso` INT(11) NULL,
  `fk_idBloque` INT NOT NULL,
  PRIMARY KEY (`idSala`, `fk_idBloque`),
  INDEX `fk_Sala_Bloque_idx` (`fk_idBloque` ASC),
  CONSTRAINT `fk_Sala_Bloque`
    FOREIGN KEY (`fk_idBloque`)
    REFERENCES `bd_udla_sig`.`Bloque` (`idBloque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_udla_sig`.`PuntosInteres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_udla_sig`.`PuntosInteres` (
  `idPuntosInteres` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NULL,
  `Longitud` FLOAT NULL,
  `Latitud` FLOAT NULL,
  PRIMARY KEY (`idPuntosInteres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_udla_sig`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_udla_sig`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_udla_sig`.`GeoHistorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_udla_sig`.`GeoHistorial` (
  `idGeoHistorial` INT NOT NULL,
  `Longitud` VARCHAR(45) NULL,
  `Latitud` VARCHAR(45) NULL,
  `fk_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idGeoHistorial`, `fk_idUsuario`),
  INDEX `fk_GeoHistorial_Usuario1_idx` (`fk_idUsuario` ASC),
  CONSTRAINT `fk_GeoHistorial_Usuario1`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `bd_udla_sig`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
